############################
## CHANGE THESE
############################

baseURL: 'https://StephenDryden.github.io/stephendryden.co.uk'
title: stephendryden.co.uk

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


